# This script takes phylum_composition.tsv generated by link_phylum.py as input file, and choose top 8 phylum and other(the rest) to draw abundance plot 

# package prepartion
library(tidyverse)

# read file
df <- read_tsv("phylum_composition.tsv")


df$colony <- factor(
  df$colony,
  levels = c("CT_A","CT_B","CT_C","CT_D","MA_A","MA_B","MA_C")
)

# only extract 8 phylum with high abundance
# because there are too many phylum in the final figure
top_n <- 8
top_phyla <- df %>%
  group_by(phylum) %>%
  summarise(total_abundance = sum(abundance)) %>%
  arrange(desc(total_abundance)) %>%
  slice_head(n = top_n) %>%
  pull(phylum)

df <- df %>%
  mutate(phylum = if_else(phylum %in% top_phyla, phylum, "Other"))

# draw plot
ggplot(df, aes(x = colony, y = abundance, fill = phylum)) +
  geom_col(width = 0.8) +
  ylab("Relative abundance") +
  xlab(NULL) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = c(RColorBrewer::brewer.pal(top_n, "Set3"), "grey70")) +
  theme_classic() +
  theme(legend.title = element_blank(), 
        legend.text = element_text(size = 8),
        legend.key.size = unit(0.5, "lines")) 
